name: Compile Keymap

on:
  workflow_dispatch: {}

permissions:
  contents: read
  actions: write

jobs:
  compile-sofle-choc:
    name: Compile sofle-choc
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli

    steps:
      - name: Install prerequisites
        run: |
          apt-get update
          apt-get install -y jq

      - name: Disable safe.directory check
        run: |
          git config --global --add safe.directory '*'

      - name: Checkout QMK Firmware
        uses: actions/checkout@v4

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Deploy submodules
        run: |
          qmk git-submodule -f

      - name: Build targets
        continue-on-error: true
        run: |
          qmk compile -e CONVERT_TO=promicro_rp2040 -kb sofle_choc -km keyboardhoarders

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: sofle-choc
          if-no-files-found: ignore
          path: |
            *.bin
            *.hex
            *.uf2
            .build/failed.*
            .failed
